services:
  deno-openai-rust-wasm-sample:
    image: deno-openai-rust-wasm-sample:latest
    build: 
      context: .
      dockerfile: ./dockerfile.dev
    volumes:
      - ./:/app
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
    tty: true
    command: tail -f /dev/null
    env_file:
      - .env.local

